apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: golang
  name: golang
spec:
  containers:
  - image: golang:1.15.2
    name: golang
    command: ["/bin/sh", "-c"]
    args:
      - apt update;
        apt install -y vim
        git clone https://github.com/ninoude/a-tour-of-go.git $GOPATH/src/github.com/ninoude/bookstore_users-api/;
        sleep 360000000;
